### PR TITLE
#50 Fix various search issues

### LINKED ISSUE #48: org.postgresql.util.PSQLException: ERROR: syntax error in tsquery: "team:foobar"
It seems that colons inside search queries produce the following postgresql exception:

`org.postgresql.util.PSQLException: ERROR: syntax error in tsquery: "team:octopus"`

### PR DESCRIPTION
**Pull request by prayerslayer**
Fixes #48, #50 
- Use english dictionary. Most of the text in the db and also searches are in English. This dictionary maps tokens to english lexemes e.g. `management` => `manag` whereas the simple dictionary doesn't (`management` => `management`), which leads to searches like `management` only matching exactly.
- Use `plainto_tsquery` which strips punctuation and inserts `&` operators instead
- Search in application id as well, it's weird to not find apps by id
- `a_matched_description` contained only matches in the description which could lead to an app be found due to a match in the subtitle and `a_matched_description` being empty. It now contains any match.

### CODE REVIEW

**Comment by hjacobs** [comment]
Uh, Travis CI build failing..

**Comment by prayerslayer** [comment]
Not anymore! \o/

File: resources/db/applications.sql [hunk 1]
```diff
@@ -39,16 +42,17 @@ SELECT a_id,
...
+                 || setweight(to_tsvector('english', COALESCE(a_subtitle, '')), 'C')
+                 || setweight(to_tsvector('english', COALESCE(a_description, '')), 'D')
                    as vector
             FROM zk_data.application
            WHERE a_last_modified <= COALESCE(:modified_before, a_last_modified)
              AND a_last_modified >= COALESCE(:modified_after, a_last_modified)
              AND a_team_id = COALESCE(:team_id, a_team_id)
              AND a_active = COALESCE(:active, a_active)) as apps,
-                 to_tsquery('simple', :searchquery) query
+                 plainto_tsquery('english', coalesce(:searchquery, '')) query
```
Comment (hjacobs) [inline resources/db/applications.sql]: `COALESCE`

**Comment by hjacobs** [comment]
:+1:
